### ISSUE TITLE
Replace black screen with chosen image when drawing

### ISSUE THREAD

**Issue by Stefi16** [hsbijarniya/image_editor_plus#10]
Hello. Is there a way for the image to stay on the screen when drawing on it?

**Comment by hsbijarniya** [comment]
You can draw and then move and zoom it as overly layer.

**Comment by ReggieMiller1** [comment]
> Ye but is it possible to still have the image in the background?

i managed to make it possible....go to line 1400 around there under 'ImageEditorDrawing' statefull widget then add the following under the 'Container':  **_decoration: BoxDecoration(color: Colors.orange,image:DecorationImage(image:MemoryImage(image.image),fit: BoxFit.cover )_**, **REMEMBER TO COMMENT OUT 'color'***
