### ISSUE TITLE
image_editor_plus depends on font_awesome_flutter ^9.0.0

### ISSUE THREAD

**Issue by RoyalCoder88** [hsbijarniya/image_editor_plus#16]
Hi friends,

How can I solve this issue: 

Because every version of image_editor_plus depends on font_awesome_flutter ^9.0.0 and myProject depends on font_awesome_flutter ^10.1.0, image_editor_plus is forbidden.

Thanks in advance!

**Comment by hsbijarniya** [comment]
Dependencies has been updated...

Upgrade to latest version

$ flutter pub upgrade

**Comment by RoyalCoder88** [comment]
@thanks now it works, thanks!
