### ISSUE TITLE
Extra space around the images

### ISSUE THREAD

**Issue by zeeshanahmad0201** [hsbijarniya/image_editor_plus#20]
I am experiencing an issue where when I pick the image it has no extra (transparent) space around but when I am done editing it has transparent space around.

Before editing:
![Before editing](https://user-images.githubusercontent.com/50322893/179226988-cbc9364d-796f-4950-b500-c1f69a0d900e.jpeg)

After editing
![After editing](https://user-images.githubusercontent.com/50322893/179227074-842ebb1e-fa8a-4185-8a32-8c2a25ea4400.jpeg)

**Comment by trupeshv** [comment]
Hello @hsbijarniya 
This issue is still open.
