### ISSUE TITLE
Update the dependency of permission_handler to 10.0.0

### ISSUE THREAD

**Issue by RoyalCoder88** [hsbijarniya/image_editor_plus#21]
Hi @hsbijarniya ,

Please update the dependency of permission_handler to 10.0.0 (latest version) I get this build error:

`Because image_editor_plus 0.1.4 depends on permission_handler ^9.2.0 and no versions of image_editor_plus match >0.1.4 <0.2.0, image_editor_plus ^0.1.4 requires permission_handler ^9.2.0.
So, because myapp depends on both image_editor_plus ^0.1.4 and permission_handler ^10.0.0, version solving failed.`

Thanks in advance!

**Comment by hsbijarniya** [comment]
Updated thanks...
