### ISSUE TITLE
Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.

### ISSUE THREAD

**Issue by sajawalFl** [hsbijarniya/image_editor_plus#23]
Flutter version `2.10.5`
Dart version `2.16.2`
Channel `Stable`

I am currently facing this issue whenever I try to import the package
<img width="625" alt="error" src="https://user-images.githubusercontent.com/108868891/179501633-3d7c58d9-e6e1-4477-be6c-0e48ab412292.png">

**Comment by hsbijarniya** [comment]
Any compilation error ?

Or these warnings only.

**Comment by sajawalFl** [comment]
> Any compilation error ?
> 
> Or these warnings only.

It happens when I'm trying to hot reload after importing the package
