### ISSUE TITLE
Brush annotations are transposed when navigating from the brush editor back to the image editor main screen.

### ISSUE THREAD

**Issue by mstich-mcmservices** [hsbijarniya/image_editor_plus#25]
If you use the brush tool and draw a circle in the center of the image, the brush annotation will be transposed to the right when you confirm the action using the check button.

The same is also true if you crop the image first and then use the brush tool.  The size of the brush annotation is too large relative to the image.

**Comment by Serena867** [comment]
I'm dealing with the same issue as the person above me.

**Comment by asafblum** [comment]
@hellomohsinhello @mstich-mcmservices @Serena867 did you find any resolution or workaround here?

**Comment by mstich-mcmservices** [comment]
> @hellomohsinhello @mstich-mcmservices @Serena867 did you find any resolution or workaround here?

Not as of yet.  I had wanted to dig into the source and see about doing a PR but simply have not had the time to do it.

**Comment by hellomohsinhello** [comment]
> @hellomohsinhello @mstich-mcmservices @Serena867 did you find any resolution or workaround here?

I end up fork this package and modifies myself. here you can find more details. https://medium.com/flutter-community/how-to-modify-an-existing-pub-package-to-use-in-your-flutter-project-4e909452ee66

**Comment by Tivadar9** [comment]
Any news on this issue?

**Comment by hsbijarniya** [comment]
fixed in v0.2.2
