### ISSUE TITLE
 Type 'ImagePickerOptions' not found.

### ISSUE THREAD

**Issue by sivaprasadnk** [hsbijarniya/image_editor_plus#28]
Error: Type 'ImagePickerOptions' not found.
../…/lib/image_picker_android.dart:174
    ImagePickerOptions options = const ImagePickerOptions(),
    ^^^^^^^^^^^^^^^^^^
Error: Couldn't find constructor 'ImagePickerOptions'.
../…/lib/image_picker_android.dart:174
    ImagePickerOptions options = const ImagePickerOptions(),
                                       ^^^^^^^^^^^^^^^^^^
Error: 'ImagePickerOptions' isn't a type.
../…/lib/image_picker_android.dart:174
    ImagePickerOptions options = const ImagePickerOptions(),
    ^^^^^^^^^^^^^^^^^^

**Comment by hsbijarniya** [comment]
Fixed as of now.
