### ISSUE TITLE
Add original author

### ISSUE THREAD

**Issue by mjablecnik** [hsbijarniya/image_editor_plus#3]
Can you tell me why did you closed my PR: https://github.com/hsbijarniya/image_editor_plus/pull/2 without any response 
where I add name of original author of the code which was used in this project??

**Comment by hsbijarniya** [comment]
Kindly cross check the project source code the author you have mentioned I have used their package initially but was not working properly.

That project was coded using firexcode package dependency that is at time of writing is much outdated and do not support null safety.

The user interface of my project is similar because I needed same kind of functionality so keep it similar intentionally.

Other than that you will not find anything similar in code.

I have implemented project as layers as opposed to single layer to make undo redo work.

I have implemented image cropping using dependency library.

I have implemented filters on my own using matrix multiplication.

You can cross check these things.

**Comment by mjablecnik** [comment]
Yes, so you continue in next development of ImageEditorPro but under different name. 
This project is not developed exactly from scratch but you took ImageEditorPro as a base.
Is it true?

> Other than that you will not find anything similar in code.

I found for example this: 
![image](https://user-images.githubusercontent.com/2686906/156930624-dc1c7050-437e-432b-a922-9d6f05f65f8b.png)
![image](https://user-images.githubusercontent.com/2686906/156930639-ddbf7eb2-b36a-4560-8cfc-39d1698e8f13.png)

Lines with:
```
TextEditingController heightcontroler = TextEditingController();
TextEditingController widthcontroler = TextEditingController();
```
Are same also with same mistake (missing one L in name of variable => heightController)

OR:
![image](https://user-images.githubusercontent.com/2686906/156930845-7dc83be4-8400-4336-b6a4-43f7beb75cb8.png)
![image](https://user-images.githubusercontent.com/2686906/156930862-1648e8c5-794f-4627-add8-ae2c02cc23da.png)

There are same names of variables, same values and exactly same comments with same indentations.

Also you have exactly same project structure:
![image](https://user-images.githubusercontent.com/2686906/156931481-f61eda3f-3f13-412e-861b-62c974ee28ca.png)
![image](https://user-images.githubusercontent.com/2686906/156931489-07a950ef-10d1-44b6-b973-4af44c52bb14.png)

And in data folder is only one dart file with only one function with same name (`getSmileys`) which return same smileys in exactly same order.

![image](https://user-images.githubusercontent.com/2686906/156931956-ce3b5e4b-5828-4a58-91de-9f4e037ab3ae.png)
![image](https://user-images.githubusercontent.com/2686906/156931969-b3d0d29a-376f-445b-9877-72790c78c3c1.png)


So It is evidence that you continue on top of ImageEditorPro project but without any mention about previous author.

**Comment by hsbijarniya** [comment]
So you are saying if you want a list of all states in Czech Republic and copy it from somewhere just for your use then you are copying someone's work ?

And project is made from scratch with some data that may needed were used if you need it, then use it otherwise don't.

Library functionality don't work via just those variables man.

**Comment by mjablecnik** [comment]
I only say that you downloaded source code of ImageEditorPro, made changes there and now you are publishing it in GitHub publicly. That is fine. But you also changed copyright of license:

![image](https://user-images.githubusercontent.com/2686906/156933869-3d11e21a-9e87-463e-93aa-7a16f7b486ed.png)
![image](https://user-images.githubusercontent.com/2686906/156933881-4a19f547-afb9-4a4d-ae4d-46865f3537a6.png)

Which violate conditions of MIT license used in the ImageEditorPro project:
```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

**Comment by hsbijarniya** [comment]
I haven't used their code man.

**Comment by hsbijarniya** [comment]
Data list doesn't entitle me to mention that according to MIT.

**Comment by mjablecnik** [comment]
And what is this?:
![image](https://user-images.githubusercontent.com/2686906/156930624-dc1c7050-437e-432b-a922-9d6f05f65f8b.png)
![image](https://user-images.githubusercontent.com/2686906/156930639-ddbf7eb2-b36a-4560-8cfc-39d1698e8f13.png)

Lines with:
```
TextEditingController heightcontroler = TextEditingController();
TextEditingController widthcontroler = TextEditingController();
```
Are same also with same mistake (missing one L in name of variable => heightController)

Or this?:
![image](https://user-images.githubusercontent.com/2686906/156930845-7dc83be4-8400-4336-b6a4-43f7beb75cb8.png)
![image](https://user-images.githubusercontent.com/2686906/156930862-1648e8c5-794f-4627-add8-ae2c02cc23da.png)

There are same names of variables, same values and exactly same comments with same indentations.

:) :)

**Comment by mjablecnik** [comment]
You continue on top of ImageEditorPro work.

**Comment by hsbijarniya** [comment]
You are saying I have downloaded source code and modified it but that was not the case.

Made it from scratch and used data where needed.

Simple

**Comment by mjablecnik** [comment]
> Made it from scratch and used data where needed.

Which data?

**Comment by hsbijarniya** [comment]
Signature controller and smiles list.

**Comment by hsbijarniya** [comment]
Firstly I want to add resize option so used heightcontroler but changed my mind and this is unused variable in the code.

**Comment by mjablecnik** [comment]
> Signature controller and smiles list.

So you admit that you used code from ImageEditorPro project?

> Firstly I want to add resize option so used heightcontroler but changed my mind and this is unused variable in the code.

Sorry but in this sentence you are indirectly saying that you took the ImageEditorPro code, changed many thinks like removed firexcode and implemented some improvements but this doesn't change that you used the ImageEditorPro code as a base for your project.

Because in developer view doesn't sense to add some code which you don't use anywhere. More probably is variant that you took the code and after refactoring and editation you forgot remove this unused code.
