### ISSUE TITLE
On IPhone 13 (tested 13 pro and Mini) check icon not visible when using Zoom

### ISSUE THREAD

**Issue by asafblum** [hsbijarniya/image_editor_plus#31]
Steps to reproduce:
Go to iPhone Settings -> Display & Brightness -> Display Zoom
Set: "Larger Text" 

Open app with image editor take a photo.
Can't apply image due to check icon not visible

Footer works fine, because it has Horizontal scroll, header action not
![IMG_7D10AE25B0FD-1](https://user-images.githubusercontent.com/1331887/212546755-6aa555e4-8416-437e-92b4-56596df2140e.jpeg)

(On iPhone 11 works fine.)

**Comment by hsbijarniya** [comment]
fixed in v0.2.2
