### ISSUE TITLE
Drawing something on image is not positioned correctly.

### ISSUE THREAD

**Issue by abhinovpankaj** [hsbijarniya/image_editor_plus#38]
I have tried using this library, everything works just fine except, the brush doesn't work as expcted.

![Simulator Screenshot - iPhone 14 Pro Max - 2023-06-01 at 11 23 14](https://github.com/hsbijarniya/image_editor_plus/assets/15319976/b56f60f1-c30c-406d-88cd-b68cca960a6d)
![Simulator Screenshot - iPhone 14 Pro Max - 2023-06-01 at 11 23 35](https://github.com/hsbijarniya/image_editor_plus/assets/15319976/26e52517-1f6b-4a8d-a3d6-1b138fc6a679)
![Simulator Screenshot - iPhone 14 Pro Max - 2023-06-01 at 11 23 41](https://github.com/hsbijarniya/image_editor_plus/assets/15319976/e77e0b83-3afe-4770-bd3d-0efa1675e7d0)

**Comment by abhinovpankaj** [comment]
Notice, the place the drawing has been made and where it appears on the actual image?

**Comment by hsbijarniya** [comment]
optimized in v0.2.2

**Comment by abhinovpankaj** [comment]
I tried the upgraded package, but the issue is not yet resolved.
More over, the brush thickness has increased which looks odd.

**Comment by yfming93** [comment]
I got the same issue
