### ISSUE TITLE
ios crashed while using filter

### ISSUE THREAD

**Issue by heshesh2010** [hsbijarniya/image_editor_plus#41]
hi , 

I'm using   image_editor_plus: ^0.2.0 , when try to use filter and drag Opacity high and low then ios crashed and got this log 

* note i tested on android and ios simulator and it works , only got this crash on real ios iphone 

from xcode :

    `Details

The app “Runner” on iPhone quit unexpectedly.
Domain: IDEDebugSessionErrorDomain
Code: 11
Failure Reason: Message from debugger: Terminated due to memory issue
User Info: {
    DVTErrorCreationDateKey = "2023-06-06 19:37:31 +0000";
    IDERunOperationFailingWorker = DBGLLDBLauncher;
}
--

Analytics Event: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_model" = "iPhone8,2";
    "device_osBuild" = "15.7.5 (19H332)";
    "device_platform" = "com.apple.platform.iphoneos";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 2;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 79884;
    "operation_errorCode" = 11;
    "operation_errorDomain" = IDEDebugSessionErrorDomain;
    "operation_errorWorker" = DBGLLDBLauncher;
    "operation_name" = IDEiPhoneRunOperationWorkerGroup;
    "param_consoleMode" = 0;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 5;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 0;
    "param_launcher_substyle" = 0;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos16.4";
    "sdk_osVersion" = "16.4";
    "sdk_variant" = iphoneos;
}
--

System Information

macOS Version 13.4 (Build 22F66)
Xcode 14.3 (21812) (Build 14E222b)
Timestamp: 2023-06-06T22:37:31+03:00`

**Comment by hsbijarniya** [comment]
not encountered with our device. please share image that caused the problem.

**Comment by devsideal** [comment]
@hsbijarniya   I'm also getting similar issue with any image, I'm using:
  
i`mage_editor_plus: ^0.2.5`
Tested in iPhone XE, iPhone 12, 6s plus. In all devices getting same issue, while in android its working fine.

**Comment by hsbijarniya** [comment]
please share the stack trace

**Comment by devsideal** [comment]
@hsbijarniya   

```
2023-08-04 17:46:48.567025+0530 Runner[3272:135397] [api] -[CIRenderDestination initWithBitmapData:width:height:bytesPerRow:format:]
 requires a valid data argument.
2023-08-04 17:46:48.568037+0530 Runner[3272:135397] [api] -[CIContext(CIRenderDestination) _startTaskToRender:toDestination:forPrepareRender:forClear:error:]
 The destination is nil.
2023-08-04 17:46:48.576935+0530 Runner[3272:135359] input size = {{0, 0}, {339, 509}}
2023-08-04 17:46:48.580792+0530 Runner[3272:135359] [api] -[CIRenderDestination initWithBitmapData:width:height:bytesPerRow:format:]
 requires a valid data argument.
2023-08-04 17:46:48.580876+0530 Runner[3272:135359] [api] -[CIContext(CIRenderDestination) _startTaskToRender:toDestination:forPrepareRender:forClear:error:]
 The destination is nil.
2023-08-04 17:46:48.593425+0530 Runner[3272:135397] input size = {{0, 0}, {339, 509}}
2023-08-04 17:46:48.609697+0530 Runner[3272:135399] input size = {{0, 0}, {339, 509}}
2023-08-04 17:46:48.627310+0530 Runner[3272:135400] input size = {{0, 0}, {339, 509}}
2023-08-04 17:46:48.632111+0530 Runner[3272:135400] IOSurface creation failed: e00002bd parentID: 00000000 properties: {
    IOSurfaceAllocateFromSuperbuffer = 0;
    IOSurfaceBytesPerElement = 4;
    IOSurfaceBytesPerRow = 1376;
    IOSurfaceCacheMode = 0;
    IOSurfaceHeight = 509;
    IOSurfaceName = CoreImage;
    IOSurfacePixelFormat = 1380401729;
    IOSurfaceProtectionOptions = 0;
    IOSurfaceWidth = 339;
}
2023-08-04 17:46:48.632224+0530 Runner[3272:135400] [render] Failed to allocate IOSurface (339x509 format:RGBA)
2023-08-04 17:46:48.632299+0530 Runner[3272:135400] [render] Cache Stats: count=0 size=0B non-volatile=0B peakCount=2 peakSize=1376KB peakNVSize=1376KB
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.
```
