### ISSUE TITLE
Drawing something on image is not positioned correctly. #38

### ISSUE THREAD

**Issue by abhinovpankaj** [hsbijarniya/image_editor_plus#45]

**Comment by GayeKone222** [comment]
Hello, Is there yet a solution for this issue ?

**Comment by GayeKone222** [comment]
Hello, Is there yet a solution for this issue ?

**Comment by remanapps** [comment]
The problem still exists
Can't draw anything on the image correctly

**Comment by hsbijarniya** [comment]
use brushOption with transatable = false for drawing with absolute position i.e. non-movable layer

brushOption added in v1.0.0
