### ISSUE TITLE
Remove unnecessary properties like flip, rotate

### ISSUE THREAD

**Issue by Louixville** [hsbijarniya/image_editor_plus#46]
Is there a way of removing properties from the main screen?

**Comment by hsbijarniya** [comment]
Use features property in ImageEditor class to enable/disable specific features

Added in v0.2.4

**Comment by hsbijarniya** [comment]
You need to pass ImageEditorFeatures object

`
ImageEditor(
...
    options: ImageEditorFeatures(
        crop: false,
    ),
);
`
 ({bool pickFromGallery = false, bool captureFromCamera = false, bool crop = false, bool blur = false, bool brush = false, bool emoji = false, bool filters = false, bool flip = false, bool rotate = false, bool text = false})
