### ISSUE TITLE
Ration customization

### ISSUE THREAD

**Issue by Pawcio93** [hsbijarniya/image_editor_plus#47]
I really love the plugin and it would be great if the ratio section could be customizable. We need 1:1 and 2:3 ratios in one of the project where in one place 1:1 ratio must be forced and in different place the 2:3 is a must. 

So it would be a great feature if we can access and change the list of ratios according to our needs

Thank you in advance!

**Comment by Gosten** [comment]
Hello, is it possible to customize ratios using ImageEditor?

Using it with ImageCropper class is pretty straightforward, but I don't see a way to implement it using ImageEditor class

**Comment by hsbijarniya** [comment]
you can pass **cropAvailableRatios** in **ImageEditor** class
