### ISSUE TITLE
image zoom in /zoom out issue and drawing bursh out side of image issue 

### ISSUE THREAD

**Issue by Sayedmdkaif** [hsbijarniya/image_editor_plus#49]
There are two issue i am having
1- We can draw brush out side the image
2- if user zoom out the image then image is very small then user can not zoom in the image 
3- if we draw on image then click on done button then drawing is not placed at accurate place

i am attaching the  video recording for above issue for better understanding.
I am using latest library version that is image_editor_plus: 0.2.4.

screen recording link
https://drive.google.com/file/d/1VddM7-xAHeHHCaA09vCeCHjMB_-sUdlp/view?usp=sharing

Please fix these issue

Thanks for advance

**Comment by hsbijarniya** [comment]
use brushOption with transatable = false

brushOption available since v1.0.0
