### ISSUE TITLE
android app crash

### ISSUE THREAD

**Issue by heshesh2010** [hsbijarniya/image_editor_plus#52]
error 

E/MediaCodecVideoRenderer(16087):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1099)
E/MediaCodecVideoRenderer(16087):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1010)
E/MediaCodecVideoRenderer(16087):       ... 11 more
I/CCodec  (16087): [c2.qti.hevc.decoder] state->set(RELEASED)
I/hw-BpHwBinder(16087): onLastStrongRef automatically unlinking death recipients
I/MediaCodec(16087): Codec shutdown complete
E/ExoPlayerImplInternal(16087): Playback error
E/ExoPlayerImplInternal(16087):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/hevc, hvc1.1.6.L150.B0, -1, null, [2160, 3840, 29.907576], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(16087):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
E/ExoPlayerImplInternal(16087):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(16087):       at android.os.Looper.loopOnce(Looper.java:226)
E/ExoPlayerImplInternal(16087):       at android.os.Looper.loop(Looper.java:313)
E/ExoPlayerImplInternal(16087):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(16087):   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.qti.hevc.decoder, Format(2, null, null, video/hevc, hvc1.1.6.L150.B0, -1, null, [2160, 3840, 29.907576], [-1, -1])
E/ExoPlayerImplInternal(16087):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1021)
E/ExoPlayerImplInternal(16087):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:537)
E/ExoPlayerImplInternal(16087):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1453)
E/ExoPlayerImplInternal(16087):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:917)
E/ExoPlayerImplInternal(16087):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:954)
E/ExoPlayerImplInternal(16087):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:769)
E/ExoPlayerImplInternal(16087):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
E/ExoPlayerImplInternal(16087):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
E/ExoPlayerImplInternal(16087):       ... 4 more
E/ExoPlayerImplInternal(16087):   Caused by: android.media.MediaCodec$CodecException: start failed
E/ExoPlayerImplInternal(16087):       at android.media.MediaCodec.native_start(Native Method)
E/ExoPlayerImplInternal(16087):       at android.media.MediaCodec.start(MediaCodec.java:2322)
E/ExoPlayerImplInternal(16087):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:160)
E/ExoPlayerImplInternal(16087):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
E/ExoPlayerImplInternal(16087):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
E/ExoPlayerImplInternal(16087):       at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:111)
E/ExoPlayerImplInternal(16087):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1099)
E/ExoPlayerImplInternal(16087):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1010)
E/ExoPlayerImplInternal(16087):       ... 11 more
2
D/MediaCodec(16087): flushMediametrics
V/FA      (16087): Inactivity, disconnecting from the service

**Comment by hsbijarniya** [comment]
exoplayer is not related to package
