### ISSUE TITLE
White Border Displayed when Selecting Black Brush

### ISSUE THREAD

**Issue by DarioAtSinov8** [hsbijarniya/image_editor_plus#54]
Phone: Samsung A24

Steps to replicate:
1. Open a photo
2. Tap on the Brush icon
3. Select purple, pink, green, blue, white, black 

Bug: When black brush is selected, a white border appears on either side of the photo

https://github.com/hsbijarniya/image_editor_plus/assets/117168592/ce7f1310-2e40-4f86-b651-7b6deda85b22

**Comment by hsbijarniya** [comment]
it was intentionally added but no use now
