### ISSUE TITLE
Dark Blue Brush displayed duplicated

### ISSUE THREAD

**Issue by DarioAtSinov8** [hsbijarniya/image_editor_plus#55]
Phone: Samsung A24

Steps to replicate:
1. Open a photo
2. Tap on the Brush icon
3. Tap on different color brushes and swipe to the end
4. Tap on dark blue brush

Bug: Two dark blue brushes are displayed and selected twice

https://github.com/hsbijarniya/image_editor_plus/assets/117168592/660d691e-db9b-47b1-b14f-438b0b953b88

**Comment by hsbijarniya** [comment]
fixed in v0.2.6
