### ISSUE TITLE
not giving actual result when editing image

### ISSUE THREAD

**Issue by sachindamco** [hsbijarniya/image_editor_plus#62]
edited overlay is not there on that point where I added overlay.

**Comment by hsbijarniya** [comment]
fixed in v1.0.0

**Comment by sachindamco** [comment]
Yes Fixed. Thanks.

but the image becomes too small after editing the overlay drawing, and when pressed done after editing, then the image shows us is increased by height. 

so there are too problems now.
1- After editing overlay drawing and back to Editing options screen, then image size become small.
2- And when we done with editing and come on main screen then Image Height is increased not actual height is there of image.
