### ISSUE TITLE
Enforcing crop ratio when other editing options are on?

### ISSUE THREAD

**Issue by Pawcio93** [hsbijarniya/image_editor_plus#71]
Hi,

We are using almost all of the image editing options and when we have them all on, we can't find a way to enforce a crop ratio on the user. For example we want that every image need to be in 1:1 ratio or some other fixed one even if user will not go to crop settings. 

We are thinking about running crop editor twice, first just for cropping and second for rest, but if it is a quick change to allow doing this at once it would be absolutely great.

**Comment by hsbijarniya** [comment]
First use ImageCropper with aspect ratio 1/1 and then pass the cropped image bytes to ImageEditor.
