### ISSUE TITLE
Add localization for texts in the image_editor_plus

### ISSUE THREAD

**Issue by frhtas** [hsbijarniya/image_editor_plus#8]
Can you add localization feature to the package? 
That would be a nice feature if we can localize ImageEditorPlus with a Map variable.

**Comment by hsbijarniya** [comment]
Sure why not...

**Comment by hsbijarniya** [comment]
This feature has been added in version v0.1.1

Kindly use this static function before using ImageEditor

ImageEditor.i18n({
   'Remove': 'हटा दीजिये',
});
