### ISSUE TITLE
Image is gone after filter is applied (white or black screen appears)

### ISSUE THREAD

**Issue by Gursewak-Uppal** [hsbijarniya/image_editor_plus#9]
Please see video..

https://drive.google.com/file/d/19Fv7QcWeVPhihIhY701KT3mkgIoQi9Lv/view?usp=sharing

**Comment by hsbijarniya** [comment]
Will be fixed in next weekly release.

**Comment by Gursewak-Uppal** [comment]
I will wait.

**Comment by Gursewak-Uppal** [comment]
Also please check the extra space added on the left and right side of the image

**Comment by Gursewak-Uppal** [comment]
How long can this problem be fixed?

**Comment by DenisMrGnusa** [comment]
same issue here,

**Comment by Gursewak-Uppal** [comment]
Any update?

**Comment by DizzasTeR** [comment]
Also waiting for a fix

**Comment by jordanmaulana** [comment]
@Gursewak-Uppal @DenisMrGnusa 
Please kindly check my PR above.
I also created solution for cases where you don't want to stack filters or you don't want it to affect your other elements like text or emojis
